# volumes:
volumes:
  mongo-data:
    external: true
services:
    mongo:
        image: mongo
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: hack reactor
            MONGO_INITDB_ROOT_PASSWORD: hacks
fastapi:
    environment:
            DATABASE_URL: mongodb://hack_reactor:secret@mongo
            DB_NAME: db-name-for-your-app-db
    CORS_HOST: http://localhost:3000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
