volumes:
  mongo-data:
    external: true

services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hacks
      MONGO_INITDB_ROOT_PASSWORD: soccer
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hacks
      ME_CONFIG_MONGODB_ADMINPASSWORD: soccer
      ME_CONFIG_MONGODB_URL: mongodb://hacks:soccer@mongo:27017/

  fastapi:
    environment:
      DATABASE_URL: mongodb://hacks:soccer@mongo:27017/
      DB_NAME: hack_reactor_hacks_db
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: ${SIGNING_KEY}
      API_KEY: ${API_KEY}
      REACT_APP_BASE_URL: /mls-monitor/
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
